### ISSUE TITLE
flathub release

### ISSUE THREAD

**Issue by tazihad** [fastrizwaan/WineZGUI#11]
Are you planning to publish this in Flathub?

**Comment by fastrizwaan** [comment]
I need good testing, could you test all features, if they are working fine, we can release on flathub.

**Comment by fastrizwaan** [comment]
This  has full filesystem access, whereas flathub won't allow full host access:
https://github.com/fastrizwaan/flatpak-wine/releases/download/0.92.8/flatpak-winezgui_0.92.8_20230226.flatpak

we need to test limited access based flatpak of winezgui. I'll look into it.
