### ISSUE TITLE
How to recreate a deleted shortcut?

### ISSUE THREAD

**Issue by Docmine17** [fastrizwaan/WineZGUI#12]
I installed a game and accidentally deleted the menu shortcut, and I would like to know how to recreate it
[Gravação de tela de 2023-10-26 12-54-11.webm](https://github.com/fastrizwaan/WineZGUI/assets/67164552/82b534df-d76d-4b13-943e-e272478b9d12)
When I click to create a prefix shortcut it goes back to the home screen

**Comment by fastrizwaan** [comment]
`WineZGUI -> More -> Recreate Prefix Scripts -> Select Bad Piggies Directory `

This will update all shortcuts and scripts (bash) required to run the game.

or even easier for all installed games

`WineZGUI -> More -> Update All Scripts`  ( this will update all scripts and restores bash files and .desktop shortcuts)

**Comment by fastrizwaan** [comment]
Could you paste the output from the terminal, open gnome-terminal, xfce4-terminal, konsole and run `flatpak run io.github.fastrizwaan.WineZGUI` and do the previous action of restoring shortcut. Please share the terminal output.

**Comment by fastrizwaan** [comment]
found the bug, flatpak needs SOURCE variable. 
```
/var/home/rizvan/.var/app/io.github.fastrizwaan.WineZGUI/data/winezgui/Prefixes/bad-piggies-1-3-0/bad-piggies-1-3-0.sh: line 4: SOURCE: command not found
grep: /var/home/rizvan/.var/app/io.github.fastrizwaan.WineZGUI/data/winezgui/Prefixes/bad-piggies-1-3-0/bad-piggies-1-3-0.desktop: No such file or directory
/var/home/rizvan/.var/app/io.github.fastrizwaan.WineZGUI/data/winezgui/Prefixes/bad-piggies-1-3-0/bad-piggies-1-3-0.sh: line 52: SOURCE: command not found
/var/home/rizvan/.var/app/io.github.fastrizwaan.WineZGUI/data/winezgui/Prefixes/bad-piggies-1-3-0/bad-piggies-1-3-0.sh: line 53: script-list-available-launch-shortcuts: command not found
/var/home/rizvan/.var/app/io.github.fastrizwaan.WineZGUI/data/winezgui/Prefixes/bad-piggies-1-3-0/bad-piggies-1-3-0.sh: line 54: : command not found
```

**Comment by fastrizwaan** [comment]
using `WineZGUI -> More -> Update All Scripts` should restore all the scripts. I'll try and fix the shortcut create bug. Thanks.

**Comment by Docmine17** [comment]
Thanks!
Some games and programs sometimes create more shortcuts than necessary... I tried to remove the shortcut from updater.exe and ended up removing the shortcut from the game by accident 😅.


![image](https://github.com/fastrizwaan/WineZGUI/assets/67164552/cb264404-3bf3-4924-8136-33f27b47e289)

**Comment by fastrizwaan** [comment]
Yes, after clean up those unwanted Shortcuts, we can create a backup (.wzt) file which can later be restored and used or can be shared with friends and family so that they don't need to worry about setting up the game.
