### ISSUE TITLE
question. how to use thise command to uninstall? 

### ISSUE THREAD

**Issue by DOOMMARINE117** [fastrizwaan/WineZGUI#18]
Hi, i tried to install winezgui through terminal since kde for me now is acting up sadly. so i couldnt use kde anymore at least tell they get it fixed.,

the command im trying to uninstall from is winezgui. 

the command i installed it. 

wget https://github.com/fastrizwaan/WineZGUI/archive/refs/tags/0.97.14.tar.gz
tar -zxvf 0.97.14.tar.gz
cd WineZGUI-0.97.14
sudo ./setup --install ; #systemwide

now how to remove it? so i can install the flatpak version?

sudo ./setup --uninstall winezgui? is that correct to remove it?

**Comment by fastrizwaan** [comment]
try installing and uninstalling again

```
sudo ./setup -i
sudo ./setup -u
```

**Comment by fastrizwaan** [comment]
yup, the flatpak version is latest which is 0.99.6 (runner support, etc.)
