### ISSUE TITLE
I cant read the menu entries completely. they're cut off short. Why??

### ISSUE THREAD

**Issue by ProfessorSparrs** [fastrizwaan/WineZGUI#19]
I cant read the menu entries completely. they're cut off short. Why?? 
![Screenshot_20240305_201515](https://github.com/fastrizwaan/WineZGUI/assets/65371358/a3fa4cb8-109a-4501-8542-26f32da4fe4f)

Is there some config somewhere so I can fix this? Theres totally tons of space left to show the full text entries for each menu entry.

Until, if you even would consider fixing this, I'll guess my way around.

Thanks for making software that could/can run windows software on Linux, the superior OS ;)
Have a good day sir, mam or whatever. :)
/Desmond

**Comment by fastrizwaan** [comment]
well the elipses `...` is there for continuation of the option selected, there is no full text, see "help..." okay!
