### ISSUE TITLE
Add AppStream metadata file

### ISSUE THREAD

**Issue by AsciiWolf** [fastrizwaan/WineZGUI#2]
Please, consider adding an AppStream metadata file for WineZGUI. It would make shipping WineZGUI to end-users much easier since the AppStream metainfo file is required by Flatpak repositories for desktop applications and also by many regular desktop package systems nowadays.

**Comment by fastrizwaan** [comment]
Sure, hope this is it?
https://freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps

**Comment by AsciiWolf** [comment]
Yep, these are the AppStream metadata. I apologize that I forgot to include this link in my comment.

**Comment by fastrizwaan** [comment]
I hope this is ok? https://github.com/fastrizwaan/WineZGUI/commit/7e209c7c79c32507c8bcc03cb6f816788189308c

created using https://www.freedesktop.org/software/appstream/metainfocreator/#/guiapp

**Comment by AsciiWolf** [comment]
You may also add `<url type="homepage">https://github.com/fastrizwaan/WineZGUI</url>`, but otherwise looks good! :-)

**Comment by fastrizwaan** [comment]
Thanks, looks like we've done it. https://github.com/fastrizwaan/WineZGUI/commit/7532a6dc07bb7a3661bb1a9f592568bd109f6289

Should we also add content-rating, if so, how?
```
 appstreamcli validate assets/io.github.fastrizwaan.WineZGUI.metainfo.xml 
I: io.github.fastrizwaan.WineZGUI:~: content-rating-missing

```

**Comment by AsciiWolf** [comment]
Sure, we can add an empty oars tag to make the AppStream parsers happy:
`<content_rating type="oars-1.1" />`
:-)

**Comment by fastrizwaan** [comment]
Yes, I do, but after 1.0 release. Thanks.
