### ISSUE TITLE
Runners: add Proton-GE

### ISSUE THREAD

**Issue by Heus-Sueh** [fastrizwaan/WineZGUI#20]
https://github.com/GloriousEggroll/proton-ge-custom

https://github.com/Open-Wine-Components/ULWGL-launcher

**Comment by fastrizwaan** [comment]
proton ge is already part of runner->download->Kron4ek wine-proton (which is recommended to be used outside steam)

ulwgl if i remember is the same proton from steam meant for different launchers.

you can import a runner into winezgui.

basically kron4ek wine proton is same and proton-ge or ulwgl.

**Comment by sonic2kk** [comment]
Hi, I came here from another issue, and wanted to clarify a few points. I realise this is an old issue though.

I am not an expert, I just keep an eye on the goings-on around Linux gaming and might be able to offer some clarification here.

- Kron4ek doesn't include DXVK or vkd3d-proton, the translation layers for running games with Vulkan for increased performance, so it is not the same as GE-Proton in that sense. See [this note](https://github.com/Kron4ek/Wine-Builds/releases/tag/proton-exp-9.0) on the Proton Experimental 9.0 release notes (it exists for the majority of their recent Proton releases as well, if not all of them). This has the benefit of allowing you to "bring-your-own-DXVK-vkd3dproton-version", which can be handy if you want to use nightly builds without worrying about Proton's script overwriting them.
- ULWGL, now named `umu`, is not Proton. [The project Readme](https://github.com/Open-Wine-Components/umu-launcher/blob/733c6abc4fe434bfee068454f5a9cb8fad033c09/README.md) has a good breakdown of what it is. It is essentially the Steam Linux Runtime provided outside of Steam to allow Non-Steam Games to run with Proton. Essentially, Proton (and all Proton flavours, including GE-Proton, Proton-tkg, and  is built against a container called the Steam Linux Runtime, which is essentially a snapshot of a given distribution with a given set of libraries, library names, versions, and paths. Think of it like having all of the libraries and tools that games need to run in one parcel, meaning that Proton doesn't have to look in your system for those libraries. This gives a consistent experience across distros, so you don't have to install packages or worry about updates breaking Proton. In theory, Proton should have the same compatibility as far as libraries are concerned regardless of distribution, as it simply targets the Steam Linux Runtime.
    - The technology underpinning the Steam Linux Runtime is called [`steam-runtime-tools`](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/tree/main), which allows you to build containers for use with Proton with the [`pressure-vessel`](https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/tree/main/pressure-vessel) container system, based heavily on Red Hat's `bwrap` (short for "Bubblewrap") that is used for Flatpaks.
    - Steam contains three set versions of the Steam Linux Runtime used in the Steam Client with version numbers and codenames referring to Team Fortress 2 classes: 1.0 Scout for native games, 2.0 Soldier for Proton 5.13 up to Proton 7, and 3.0 Sniper for Proton 8.0+ and also for native games (although currently you can only use it for native games by manually setting `steamlinuxruntime_sniper` in your Steam `config.vdf`'s `CompatToolMapping` section). You can check what version of the Steam Linux Runtime a Proton version requires by checking the `toolmanifest.vdf` of a Proton version's folder, and examining the `require_tool_appid`. In future, there may be a 4.0 runtime, so this information may be useful if you want to check that.
    - `umu` is just a packaged version of the Steam Linux Runtime 3.0 Sniper that can be used outside of the Steam Client, and the entire purpose of this is to allow reliable Proton usage outside of Steam. In other words, using the `umu` wrapper, you should get the same experience using Proton as you would with using it inside of Steam. The ultimate benefit here is that there is no need for something like Wine-GE, which attempts to apply all of Valve's Proton patches and improvements on top of their Wine fork without the reliance on the Steam Linux Runtime.
        - As an extra aside, popular launchers like Lutris and Heroic would already look for the Steam Linux Runtime required by a given Proton version from the Steam Client. `umu` negates the need for this though, as it essentially replaces the Steam Linux Runtime for Proton outside of Steam.
    - `umu` appears to also allow you to pass a game ID specific to `umu` via a commandline flag, which allows it to apply specific fixes using Protonfixes. GE-Proton can do this based on AppID and in some cases EXE name, but as EXE names are not as reliable of an identifier outside of Steam, passing this specific pre-defined ID that `umu` specifically looks for allows for these fixes. The list of available hardcoded identifiers that `umu` looks for is supposed to be [available here](https://ulwgl.openwinecomponents.org/) a website linked on the [releases page](https://github.com/Open-Wine-Components/umu-launcher/releases/tag/0.1-RC3), but it is currently unavailable.
    - UMU will eventually allow, or may already allow, for Proton to reliably be used outside of Steam, as launchers can use it. Proton flavours may also be able to use it, for example GE-Proton may already include it, but I am not sure on this. In other words, I don't think WineZGUI has to do anything to allow or enable UMU, it should be handled by GE-Proton. It would only be relevant to handle if you were making a custom compatibility tool I believe.

I hope this helps offer some additional info!
