### ISSUE TITLE
Consider using ShellCheck on Scripts

### ISSUE THREAD

**Issue by sonic2kk** [fastrizwaan/WineZGUI#21]
Hello!

I maintain a tool similar to WineZGUI for use with Steam, and there is a very useful code analysis tool I use during development called [ShellCheck](https://github.com/koalaman/shellcheck). This can be integrated into different editors/IDEs (such as Kate with the Bash Language Server plugin, or VSCode with some plugins), or it can be used from the commandline with `shellcheck /path/to/script`.

ShellCheck will examine a given script and tell you what the problem is, and give you a link to its own wiki page where ShellCheck tells you what the issue is, why you should fix it, cases where you might not want to fix it, and usually also provides snippets of bad code and fixed code. For example, `bin/winezgui` contains some `SC2086` warnings around globbing, and you can find more about it by going to https://shellcheck.net/wiki/SC2086. The format of the wiki links is always the same, except the ShellCheck `SC` code changes :-)

The tool is very handy at picking up on potential issues that could come up, sometimes it is a bit *too* helpful though and needs to be told to be quiet as there are instances where the developer knows better :wink: You can set this with directives. You put a directive to disable the warning above the given line as a comment, for example `#shellcheck disable=SC2086` would silence the warning for that line.

This is just a tip from one Bash user to another, and it may help with code maintenance over time. But maybe you have a good reason for not using ShellCheck and that's totally fine. This isn't a demand, just a suggestion. If you'd like, I could help out submitting PRs to attempt to fix the ShellCheck warnings.

Thanks!

**Comment by fastrizwaan** [comment]
Thank you, you're very kind. Please do PRs for such issues. I'll be glad.

**Comment by sonic2kk** [comment]
All good! I have submitted two PRs: #22 to add shebang(s), and #23 which contains "real" changes. I will only open these two PRs for now, to allow for discussion that will inform the best way moving forward on these (for example, how you would prefer to break up PRs).

**Comment by fastrizwaan** [comment]
Thanks @sonic2kk I've merged them, will test the changes.

**Comment by sonic2kk** [comment]
Thanks for all the review on the PRs so far! Sorry it's been a bit of a slow process even though I suggested this. I will work through the files as I have time :-)
