### ISSUE TITLE
How to only create one prefix when launhing exe? Or only have one prefix from where I use all my exe? 

### ISSUE THREAD

**Issue by Saigaiii** [fastrizwaan/WineZGUI#29]
Basically the title. Not sure how I would go about this.

**Comment by fastrizwaan** [comment]
WineZGUI is designed to isolate prefixes for different exes, so that they can be bundled/shared. It also prevents one exe to mess up the registry and / or overwrite working dlls of other exes.

You can use Open Other exe of an existing script to achieve the 1 prefix multiple exes. or manually edit the script file and set the wineprefix.

**Comment by Saigaiii** [comment]
Ok thank you. Another question, is there a way to copy a prefix into a prefix created by winezgui? I ask this because I already have a prefix created with an exe I wanted to use with all the dependencies installed and need to see if there is a way to transfer that wine directory to the exe when used with winezgui. I cannot find an option when launching an exe with winezgui, assuming because it already creates its own prefix. If I run winezgui, I can import a wine directory but it prompts to use an exe with it and I cannot choose the exe I want to use it with.

**Comment by fastrizwaan** [comment]
You can copy the prefix as template and set the template there. but then again it will create copy of that template every time.

OK, I'll try to implement "Use a Single Prefix for All EXEs" in Settings. perhaps in a few days.

**Comment by fastrizwaan** [comment]
I've updated WineZGUI with "Single Prefix" in settings. Select "Yes" in Settings->Use Single Prefix for All Exes; Then afterwards all exe files opened will be using a single prefix, i.e., WineZGUI-Single-Prefix directory in the Prefixes directory.

https://github.com/flathub/io.github.fastrizwaan.WineZGUI/pull/38
